[package]
name = "virtio-input-decoder"
version = "0.1.3"
authors = ["belowthetree <1363558876@qq.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "A simple decoder for virtio keyboard and mouse"
repository = "https://github.com/belowthetree/virtio-input-decoder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
